export const DEETS_LIST_REQUEST = 'DEETS_LIST_REQUEST'
export const DEETS_LIST_SUCCESS = 'DEETS_LIST_SUCCESS'
export const DEETS_LIST_FAIL = 'DEETS_LIST_FAIL'

export const DEETS_CREATE_REQUEST = 'DEETS_CREATE_REQUEST'
export const DEETS_CREATE_SUCCESS = 'DEETS_CREATE_SUCCESS'
export const DEETS_CREATE_FAIL = 'DEETS_CREATE_FAIL' 

export const DEETS_UPDATE_REQUEST = 'DEETS_UPDATE_REQUEST'
export const DEETS_UPDATE_SUCCESS = 'DEETS_UPDATE_SUCCESS'
export const DEETS_UPDATE_FAIL = 'DEETS_UPDATE_FAIL' 

export const DEETS_DELETE_REQUEST = 'DEETS_DELETE_REQUEST'
export const DEETS_DELETE_SUCCESS = 'DEETS_DELETE_SUCCESS'
export const DEETS_DELETE_FAIL = 'DEETS_DELETE_FAIL' 